<?php

declare(strict_types=1);

namespace Ayimdomnic\Laragraph\Tests\Console;

use Ayimdomnic\Laragraph\Scalars\DateTimeType;
use Ayimdomnic\Laragraph\Tests\TestCase;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Schema;

/**
 * Runs code generated by `laragraph:scaffold --with-crud` end to end.
 */
class ScaffoldSecurityTest extends TestCase
{
    private bool $createdModelsDirectory = false;

    protected function defineEnvironment($app): void
    {
        parent::defineEnvironment($app);

        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', ['driver' => 'sqlite', 'database' => ':memory:', 'prefix' => '']);
        $app['config']->set('laragraph.types', [
            'DateTime' => DateTimeType::class,
        ]);
    }

    protected function setUp(): void
    {
        parent::setUp();

        File::deleteDirectory(app_path('GraphQL'));
        $this->createdModelsDirectory = !is_dir(app_path('Models'));
        File::ensureDirectoryExists(app_path('Models'));
        file_put_contents(app_path('Models/ScaffoldWidget.php'), <<<'PHP'
<?php
namespace App\Models;
class ScaffoldWidget extends \Illuminate\Database\Eloquent\Model {
    protected $fillable = ['name', 'secret_token'];
    protected $hidden   = ['secret_token'];
}
PHP);
        require_once app_path('Models/ScaffoldWidget.php');

        Schema::create('scaffold_widgets', function ($table): void {
            $table->id();
            $table->string('name')->nullable();
            $table->string('secret_token')->nullable();
            $table->timestamps();
        });
        DB::table('scaffold_widgets')->insert(['name' => 'first', 'secret_token' => 's3cr3t']);

        $this->artisan('laragraph:scaffold', ['model' => 'App\\Models\\ScaffoldWidget', '--with-crud' => true])->assertSuccessful();

        foreach (['Types/ScaffoldWidgetType', 'Queries/ScaffoldWidgetQuery', 'Queries/ScaffoldWidgetsQuery', 'Mutations/CreateScaffoldWidgetMutation', 'Mutations/UpdateScaffoldWidgetMutation', 'Mutations/DeleteScaffoldWidgetMutation'] as $file) {
            require_once app_path("GraphQL/{$file}.php");
        }

        config([
            'laragraph.types.ScaffoldWidget' => 'App\\GraphQL\\Types\\ScaffoldWidgetType',
            'laragraph.schemas.default'      => [
                'query' => [
                    'scaffoldWidget'  => 'App\\GraphQL\\Queries\\ScaffoldWidgetQuery',
                    'scaffoldWidgets' => 'App\\GraphQL\\Queries\\ScaffoldWidgetsQuery',
                ],
                'mutation' => [
                    'createScaffoldWidget' => 'App\\GraphQL\\Mutations\\CreateScaffoldWidgetMutation',
                    'updateScaffoldWidget' => 'App\\GraphQL\\Mutations\\UpdateScaffoldWidgetMutation',
                    'deleteScaffoldWidget' => 'App\\GraphQL\\Mutations\\DeleteScaffoldWidgetMutation',
                ],
            ],
        ]);
        $this->app->forgetInstance('laragraph');
    }

    protected function tearDown(): void
    {
        File::deleteDirectory(app_path('GraphQL'));
        File::delete(app_path('Models/ScaffoldWidget.php'));

        if ($this->createdModelsDirectory) {
            File::deleteDirectory(app_path('Models'));
        }

        parent::tearDown();
    }

    /**
     * @return array<string, string> operation => GraphQL document
     */
    private function operations(): array
    {
        return [
            'scaffoldWidget'       => '{ scaffoldWidget(id: 1) { id name } }',
            'scaffoldWidgets'      => '{ scaffoldWidgets(first: 5) { edges { node { id } } } }',
            'createScaffoldWidget' => 'mutation { createScaffoldWidget(name: "x") { id } }',
            'updateScaffoldWidget' => 'mutation { updateScaffoldWidget(id: 1, name: "y") { id } }',
            'deleteScaffoldWidget' => 'mutation { deleteScaffoldWidget(id: 1) }',
        ];
    }

    public function test_hidden_attributes_are_not_exposed_by_the_generated_type(): void
    {
        $type = (string) file_get_contents(app_path('GraphQL/Types/ScaffoldWidgetType.php'));
        $create = (string) file_get_contents(app_path('GraphQL/Mutations/CreateScaffoldWidgetMutation.php'));

        $this->assertStringContainsString("'name'", $type);
        $this->assertStringNotContainsString('secret_token', $type);
        // Still accepted as mutation input — just never readable back.
        $this->assertStringContainsString("'secret_token'", $create);

        $fields = array_column($this->graphql('{ __type(name: "ScaffoldWidget") { fields { name } } }')['data']['__type']['fields'], 'name');
        $this->assertNotContains('secret_token', $fields);
    }

    public function test_generated_operations_deny_guests(): void
    {
        foreach ($this->operations() as $operation => $document) {
            $result = $this->graphql($document);

            $this->assertSame('authorization', $result['errors'][0]['extensions']['category'] ?? null, $operation . ': ' . json_encode($result));
        }

        $this->assertSame(1, DB::table('scaffold_widgets')->count());
    }

    public function test_generated_operations_deny_users_without_a_grant(): void
    {
        $this->actingAs((new User())->forceFill(['id' => 1]));

        foreach ($this->operations() as $operation => $document) {
            $result = $this->graphql($document);

            $this->assertSame('authorization', $result['errors'][0]['extensions']['category'] ?? null, $operation);
        }
    }

    public function test_generated_operations_run_once_a_policy_or_gate_grants_them(): void
    {
        $this->actingAs((new User())->forceFill(['id' => 1]));

        foreach (['view', 'viewAny', 'create', 'update', 'delete'] as $ability) {
            Gate::define($ability, fn(): bool => true);
        }

        foreach ($this->operations() as $operation => $document) {
            $result = $this->graphql($document);

            $this->assertArrayNotHasKey('errors', $result, $operation . ': ' . json_encode($result));
        }

        $this->assertSame(1, DB::table('scaffold_widgets')->count()); // one created, one deleted
    }

    public function test_missing_records_are_denied_rather_than_revealed(): void
    {
        $this->actingAs((new User())->forceFill(['id' => 1]));
        Gate::define('delete', fn(): bool => true);

        $result = $this->graphql('mutation { deleteScaffoldWidget(id: 999) }');

        $this->assertSame('authorization', $result['errors'][0]['extensions']['category'] ?? null);
    }
}
